'use client'
import { FormEvent, useCallback, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { Loader2, Users } from 'lucide-react'
import { getAppAuthHeaders, getCurrentAppUser } from '@/lib/app-auth'

type Member = { id: string; email: string; role: 'admin' | 'member'; status: 'invited' | 'active'; created_at: string }
export default function TeamPage() {
  const router = useRouter(); const [members, setMembers] = useState<Member[]>([]); const [loading, setLoading] = useState(true); const [email, setEmail] = useState(''); const [role, setRole] = useState<'admin' | 'member'>('member'); const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  const load = useCallback(async () => { const response = await fetch('/api/team/members', { headers: await getAppAuthHeaders() }); if (response.status === 401) return router.replace('/login?next=%2Ftim'); if (response.status === 403) return router.replace('/ucet'); if (response.ok) setMembers((await response.json()).members ?? []); else setError('Tím sa nepodarilo načítať.'); setLoading(false) }, [router])
  useEffect(() => { void (async () => { if (!await getCurrentAppUser()) return router.replace('/login?next=%2Ftim'); await load() })() }, [router, load])
  async function invite(event: FormEvent) { event.preventDefault(); setError(''); setNotice(''); const response = await fetch('/api/team/members', { method: 'POST', headers: { 'Content-Type': 'application/json', ...await getAppAuthHeaders() }, body: JSON.stringify({ email, role }) }); const payload = await response.json(); if (!response.ok) { setError(payload.error || 'Pozvánku sa nepodarilo pridať.'); return } setNotice(payload.emailSent ? 'Pozvánka bola odoslaná e-mailom.' : 'Člen je pridaný ako pozvaný. E-mail sa nepodarilo odoslať, skontrolujte nastavenie Resend.'); setEmail(''); await load() }
  if (loading) return <div className="flex min-h-[calc(100vh-72px)] items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-[#2563EB]" /></div>
  return <div className="mx-auto w-full max-w-4xl px-5 py-10 sm:px-8"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-[#2563EB]">Firemný účet</p><h1 className="mt-2 text-4xl font-extrabold text-[#020617]">Tím</h1><p className="mt-3 text-sm text-slate-500">Administrátori spravujú firemné nastavenia; zamestnanci majú prístup k pracovným analýzam.</p><form onSubmit={invite} className="mt-8 flex flex-col gap-3 rounded-3xl border border-slate-200 bg-white p-5 sm:flex-row"><input value={email} onChange={(event) => setEmail(event.target.value)} type="email" required placeholder="kolega@firma.sk" className="h-11 flex-1 rounded-xl border border-slate-200 px-3 text-sm" /><select value={role} onChange={(event) => setRole(event.target.value as 'admin' | 'member')} className="h-11 rounded-xl border border-slate-200 px-3 text-sm"><option value="member">Zamestnanec</option><option value="admin">Administrátor</option></select><button className="h-11 rounded-xl bg-[#020617] px-5 text-sm font-bold text-white">Poslať pozvánku</button></form>{error && <p className="mt-3 text-sm font-bold text-red-600">{error}</p>}{notice && <p className="mt-3 text-sm font-bold text-emerald-700">{notice}</p>}<section className="mt-8 overflow-hidden rounded-3xl border border-slate-200 bg-white">{members.length ? members.map((member) => <div key={member.id} className="flex items-center gap-3 border-b border-slate-100 px-5 py-4 last:border-0"><Users className="h-4 w-4 text-[#2563EB]" /><div className="flex-1"><p className="text-sm font-bold text-[#020617]">{member.email}</p><p className="mt-1 text-xs text-slate-400">{member.role === 'admin' ? 'Administrátor' : 'Zamestnanec'} · {member.status === 'invited' ? 'Pozvaný' : 'Aktívny'}</p></div></div>) : <p className="px-5 py-12 text-center text-sm text-slate-500">Zatiaľ nemáte žiadnych členov tímu.</p>}</section></div>
}
